server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_bd
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Service user"
appVersion: "1.0.0"

logging:
  level:
    org:
      springframework:
        security: DEBUG
